air_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - s1j
    - s2j
    - s3j
    - ej
    - rollj
    - pitchj
    - yawj
  gains:
    s1j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    s2j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    s3j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ej:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rollj:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    pitchj:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yawj:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

