amr:
  ads_config:
    remote_ipv4: "1"
    remote_net_id: "2"
    local_adress:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
    port_num: 851
    symbols:
      left_encoder: "left_encoder_symbol"
      right_encoder: "right_encoder_symbol"

      left_motor: "left_motor_symbol"
      right_motor: "right_motor_symbol"
      
      wheels:
        left:
          vel: ""
          pos: ""
        
        right:
          vel: ""
          pos: ""


  hardware_interface:
    joints:
    - "left_wheel_joint_name"
    - "right_wheel_joint_name"
    loop_hz: 50
    encoders:
      resolution: 18
