amr:
  ads_config:
    #remote_ipv4: "172.34.6.72"
    remote_ipv4: "169.254.71.135"
    remote_net_id: "172.18.212.67.1.1"
    local_adress:
      - 172
      - 34
      - 6
      - 69
      - 1
      - 1
    port_num: 851
    symbols:
      left_encoder: "GVL.fActVel_R"
      right_encoder: "GVL.fActVel_L"

      left_motor: "left_motor_symbol"
      right_motor: "right_motor_symbol"

      linear_vel: "GVL.fRefLin"
      angular_vel: "GVL.fRefAng"
      
      
      drive_status: "GVL.bEnable"

      wheels:
        left:
          vel: ""
          pos: ""
        
        right:
          vel: ""
          pos: ""


  hardware_interface:
    joints:
    - "lw_joint"
    - "rw_joint"
    loop_hz: 50
    encoders:
      resolution: 18
